[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run start"
  port = 8888
  targetPort = 1234
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 